{% set name = "logging_tree" %}
{% set version = "1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cd78848fe0ee4aafcc64fa8a66f96f177186ff3d883619b1d7f3628564802095

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -v --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  requires:
    - pip
  imports:
    - logging_tree
  commands:
    - pip check

about:
  home: https://github.com/brandon-rhodes/logging_tree
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYRIGHT
  summary: Introspect and display the logger tree inside "logging"
  description: Introspection for the `logging` logger tree in the Standard Library.
  doc_url: https://github.com/brandon-rhodes/logging_tree/blob/master/README.md
  dev_url: https://github.com/brandon-rhodes/logging_tree

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
